Inputs:
    - j1_ptrel
    - j1_etarot
    - j1_phirot
    - j1_erel
    - j1_deltaR
    - j1_costhetarel
    - j1_pdgid
    - j_pt
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    - j_pt
    
KerasModel: conv1d_model
KerasModelRetrain: conv1d_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0
NormalizeInputs: 1
ConvInputs: 1
MaxParticles: 100
