Inputs:
    - j1_ptrel
    - j1_etarot
    - j1_phirot
    - j1_erel
    - j1_deltaR
    - j1_pdgid
    - j_index
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    - j_index
    
KerasModel: lstm_model
KerasModelRetrain: rnn_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0
NormalizeInputs: 1
InputType: Conv1D
MaxParticles: 50
